logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka/